### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by figgefidge** [patrickmonteiro/quasarOidcClient#1]
Hi, great initiative implementing this library!
However, I am getting an error when compiling...
The error I am getting is:
Syntax error: security-oidc.js: 'import' and 'export' may only appear at the top level (67:0)

I am using npm 6.4.1, node 8.12.0 and quasar 0.17.19

**Comment by patrickmonteiro** [comment]
Hi, I'll check it out!

**Comment by patrickmonteiro** [comment]
Fixed problem in security-oidc plugin [e846529](https://github.com/patrickmonteiro/quasarOidcClient/commit/e8465294199c79065a3791eeecbf16f7cec78646)
